apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: trustyai-explainability-xdg6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: trustyai-explainability-xdg6
    app.kubernetes.io/part-of: opendatahub
  name: trustyai-explainability-xdg6
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: trustyai-explainability-xdg6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: trustyai-explainability-xdg6
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/pablo-rhods-tenant/opendatahub/trustyai-explainability-xdg6@sha256:293ac650cd283f4ea4126da3de2774bb4b76ec0809f23056ea78a3d610fe9cde
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
